default_platform(:ios)

platform :ios do
  desc "CI Build Without Signing"
  lane :build_local do
    build_app(
      scheme: "CICD_Pipelines",
      skip_archive: true,
      skip_package_ipa: true,
      xcargs: "CODE_SIGNING_ALLOWED=NO"
    )
  end
end