default_platform(:ios)

platform :ios do

  desc "Build IPA and save to Downloads"
  lane :build_local do
    gym(
      scheme: "CICD_Pipelines",
      export_method: "development",
      output_directory: File.expand_path("~/Downloads"),
      output_name: "CICD_Pipelines.ipa",
      clean: true
    )
  end

end